### ISSUE TITLE
Разобраться с формированием множественного числа для OData

### ISSUE THREAD

**Issue by DubrovinPavel** [Flexberry/ember-flexberry-data#142]
### Цель
Разобраться с формированием множественного числа для OData

### Функциональные требования
1) Множественное число должно формироваться просто добавлением 's' на конце без склонений.
2) Желательно чтобы inflector-rules продолжали работать. 

### Требования к реализации
В odata адаптере есть метод pathForType. Возможно стоит в нем использовать свой метод для приведения ко множественному числу.

**Comment by KollegOFF** [comment]
Давно предлагаю избавиться от `custom-inflector-rules`, одни проблемы от этого костыля.
Нужно [в адаптере](https://github.com/Flexberry/ember-flexberry-data/blob/76a122ccf03a240b556f8aba58e3c4b36c9d19b0/addon/adapters/odata.js#L175), не использовать плюрализацию, а просто добавлять `s` к имени модели, так же как это делается в [ODataService](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/blob/918e88755043682c48f2a7c2eb75d325af0c48ca/NewPlatform.Flexberry.ORM.ODataService/Model/DefaultDataObjectEdmModelBuilder.cs#L263).
