### ISSUE TITLE
Теряются сообщения ошибок в batchUpdate

### ISSUE THREAD

**Issue by aleksanderMinin** [Flexberry/ember-flexberry-data#147]
### Описание ошибки
Объект ошибки приводится к строке, поэтому сообщение из ошибки не получается обработать и показать пользователю.

### Ожидаемое поведение
При наличии ошибок, в ответе на batchUpdate, возвращать объект ошибки.

### Пути решения
При поиске ошибок в ответе возвращать DS.AdapterError

### Исходный код
[https://github.com/Flexberry/ember-flexberry-data/](https://github.com/Flexberry/ember-flexberry-data/)
Наследоваться от develop

### Документация
- [Поиск ошибок в batchUpdate](https://github.com/Flexberry/ember-flexberry-data/blob/1045e9e7218db73d46c22577fb1848953af44c14/addon/adapters/odata.js#L503)
- [DS.AdapterError](https://api.emberjs.com/ember-data/2.4/classes/DS.AdapterError)

**Comment by PashaMasalkin** [comment]
https://github.com/Flexberry/ember-flexberry-data/pull/150
